### PR TITLE
Admin and accessibility tool

### PR DESCRIPTION
**Pull request by safatshahin**
PR for changes to accessibility tool and too health

### CODE REVIEW

**Comment by guillogo** [comment]
Hi @safatshahin thank you for this PR.

Queries: OK

1. The changes for tool_health are correct despite Moodle doesn't support the plugin anymore.

2. About, tool_brickfield the queries are correct, however I have a question: why we decide to move the queries to core_questions as they already have their own class structure coded in a good way?, also if the new class created in this PR will be only for that plugin I'd think that is better to change the queries there, but probably you have more information or an instruction to do it in that way. Please let me know.

Thank you.

**Comment by safatshahin** [comment]
Hi @guillogo 
Thanks for your review of this. Moving the question in core_question was just an approach to have its own interface for any plugins. But after going through some other areas, it feels a little too much. My idea was that any plugin that wants to use a question, will need to use an existing interface to get any data. 
I will move them back to the tool itself.
I can see tool_helth is still available, not changing it might break that page.
Cheers!

**Comment by safatshahin** [comment]
Hi @guillogo 
The changes are done. Please give it another go. 
Cheers!

**Review by guillogo — APPROVED** [review]
Thank you @safatshahin for the changes.

Approved after:
- testing each query.
- Execute unit test

I'll merge this PR but we will do user test after push it into the testsite as the API key is not working for localhost.

Thank you.

**Pull request merged**
