### PR TITLE
Create default question categories only for current context

### PR DESCRIPTION
**Pull request by guillogo**
This PR will close issue: 205

### CODE REVIEW

**Comment by guillogo** [comment]
Hi, unit test added to PR. Thank you.

**Review by safatshahin — COMMENTED** [review]
Hi @guillogo 
PR looks good. There are some strings that were used in the core_course as a part of the question which is not in use anymore.  Can you please check if they're used somewhere else? if not those strings need to be deprecated. I could see one of them can be deprecated, but its worth looking at all of them.

Cheers!

**Comment by guillogo** [comment]
Hi @safatshahin thank you for reviewing, the strings have been deprecated following the https://docs.moodle.org/dev/String_deprecation. Thank you.

**Comment by safatshahin** [comment]
PR merged, thank you.
Please squash the commits in the base branch so that it can be added to other branches like the testsite.
Cheers!

**Pull request merged**
