### PR TITLE
Master mdl 71696 21

### PR DESCRIPTION
**Pull request by guillogo**
Add new tables:

**Tables created:**

question_bank_entry
question_versions
question_references
question_set_references

### CODE REVIEW

**Comment by guillogo** [comment]
Hi, the question_reference is now populated. Thank you.

TODO:
1. Populate table question_set_references.
2. Remove fields from question table.
3. Improve privacy/provider class.

**Comment by safatshahin** [comment]
Hi @guillogo 
thank you for your work in this.
As of our discussion,
please add the json in the filtercondition and remove the version.

**Comment by guillogo** [comment]
Hi @safatshahin 

Thank you for looking into this. Done:

1. Version conflict fixed.
2. json added to filtercondition.

Thank you.
Guillermo

**Comment by safatshahin** [comment]
PR merged, thank you

**Pull request merged**
