### PR TITLE
Master mdl 72321 api changes 49 - date filter

### PR DESCRIPTION
**Pull request by marcghaly**
Hi @safatshahin, these are changes for this issue https://github.com/catalyst/moodle-MDL-70329/issues/49, they also include a fix for no arguments passed (as part of the separation between `qbank_filter` and the fragment call), it also include the `range` changes and finally `issue 49`: filter by date. There are 3 different commits, only last one is relevant to this issue.

Cheers!

### CODE REVIEW

**Comment by safatshahin** [comment]
Looks good, please resolve the grunt issue, will merge after 431 is merged.

**Comment by marcghaly** [comment]
Grunt fixed, branch rebased over 431. 
Cheers!

**Comment by tuanngocnguyen** [comment]
I have tested and the date filter works.
The code looks fine to me.
I am having a look on error in unit test

**Comment by tuanngocnguyen** [comment]
Rebased over master_MDL-72321-api-changes as range filter has been merged to upstream

**Comment by tuanngocnguyen** [comment]
The MR looks good to me

**Pull request merged**
