### PR TITLE
Remove question fields

### PR DESCRIPTION
**Pull request by guillogo**

### CODE REVIEW

**Comment by safatshahin** [comment]
Hi @guillogo 
PR looks good, please squash the commits and replace the commit in the master_MDL-71696-versioning branch.
Cheers

**Comment by guillogo** [comment]
Hi, quiz_slots and quiz_slot_tags changes done. Thank you.

**Comment by safatshahin** [comment]
Holding this PR for now, will merge it after making all the unit test fix.

**Comment by guillogo** [comment]
Closing this PR, replaced with: https://github.com/catalyst/moodle-MDL-70329/pull/258

**Pull request closed without merging**
