### PR TITLE
Master mdl 71615 82

### PR DESCRIPTION
**Pull request by safatshahin**
PR for #82

### CODE REVIEW

**Review by guillogo — COMMENTED** [review]
Hi @safatshahin 

Tested and looks good. The only thing is to add the validation if the plugin is enabled or disabled at the beginning on the script to avoid access via url.

Thank you.

**Comment by safatshahin** [comment]
Hi @guillogo 
Thank you for reviewing this, made the changes. please have a look now.
Thanks

**Review by guillogo — APPROVED** [review]
Approved.

**Comment by guillogo** [comment]
Hi @safatshahin approved and merged. Thank you.

**Pull request merged**
